architecture:
  name: folding-net
  module_params:
    pe_type: sphere
    num_features: 512
    quantize: !root_include "../quantize.yaml"
  load_ckpt: !link checkpoints->foldingnet512

dataloader-test:
  name: default-dl
  dl_params:
    split: "test"
    h5_path: !link data->H5_PATH_FULL
    batch_size: 1