architecture:
  name: folding-net
  module_params:
    pe_type: sphere
    num_features: 128
    quantize: !root_include "../quantize.yaml"
  load_ckpt: !link checkpoints->foldingnet128

dataloader-test:
  name: default-dl
  dl_params:
    split: "test"
    batch_size: 1