architecture:
  name: gae
  module_params:
    num_features: 128
    hyper_sphere: true
    film_flag: false
    quantize: !root_include "../quantize.yaml"
  load_ckpt: !link checkpoints->gae128

dataloader-test:
  name: default-dl
  dl_params:
    split: "test"
    batch_size: 1